name: Publish Maven

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  create-release:
     if: ${{ github.repository == 'getspherelabs/blahblah' }}
     runs-on: ubuntu-latest
     steps:
       - name: Check out code
         uses: actions/checkout@v3.1.0
       - name: Extract release notes
         id: release_notes
         uses: ffurrer2/extract-release-notes@v1

       - name: Create release
         uses: softprops/action-gh-release@v1
         with:
          body: ${{ steps.release_notes.outputs.release_notes }}
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: create-release
    if: ${{ github.repository == 'getspherelabs/blahblah' }}
    strategy:
      matrix:
        os: [ macos-11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache gradle, wrapper and buildSrc
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ matrix.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/cache
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
            ~/.konan/kotlin-native-mingw*
            ~/.konan/kotlin-native-windows*
            ~/.konan/kotlin-native-linux*
            ~/.konan/kotlin-native-prebuilt-macos*
            ~/.konan/kotlin-native-prebuilt-mingw*
            ~/.konan/kotlin-native-prebuilt-windows*
            ~/.konan/kotlin-native-prebuilt-linux*
          key: ${{ matrix.os }}-konan-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ matrix.os }}-konan-
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Release build
        run: ./gradlew ./gradlew :blahblah-fake:build -x ktlintCommonMainSourceSetCheck -x ktlintKotlinScriptCheck  :blahblah-yaml:build -x ktlintCommonMainSourceSetCheck -x ktlintKotlinScriptCheck
      - name: Publish release
        run: ./gradlew publish --stacktrace
        if: contains(matrix.os, 'macos')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
